### ISSUE TITLE
Recent quantum fios update forces https over a self signed cert causing program to fail

### ISSUE THREAD

**Issue by PeterPlatt** [cisasteelersfan/quantum_gateway#7]
I recently got a router update for my Fios Quantum Gateway it appears to force https. This breaks the code in its current form. Consider updating the code to use https instead of http and ignore the self-signed cert warnings. I am not experienced in python, but I was able to get the code to work by doing that in the sample below.  

```py
import hashlib
import json
import requests
import urllib3

from http.cookies import SimpleCookie

TIMEOUT = 5

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


class QuantumGatewayScanner:
    def __init__(self, host, password):
        self.host = 'https://' + host
        self.password = password
        self.connected_devices = {}
        self.verify = False
        self.session = requests.Session()

        self.success_init = self._check_auth()

    def scan_devices(self):
        self.connected_devices = {}
        if self._check_auth():
            self._get_connected_devices()
        return self.connected_devices.keys()

    def get_device_name(self, device):
        return self.connected_devices.get(device)

    def _get_connected_devices(self):
        devices_raw = self.session.get(self.host + '/api/devices', timeout=TIMEOUT, verify=False)
        devices = json.loads(devices_raw.text)
        self.connected_devices = {device['mac']: device['name'] for device in devices if device['status']}

    def _check_auth(self):
        res = self.session.get(self.host + '/api/devices', timeout=TIMEOUT, verify=False)
        if res.status_code == 200:
            return True

        getLogin = self.session.get(self.host + '/api/login', timeout=TIMEOUT, verify=False)
        salt = getLogin.json()['passwordSalt']

        encodedPassword = hashlib.sha512()
        encodedPassword.update((self.password + salt).encode('ascii'))

        payload = json.dumps({"password": encodedPassword.hexdigest()})

        postLogin = self.session.post(self.host + '/api/login', data=payload, timeout=TIMEOUT, verify=False)
        token = SimpleCookie(postLogin.headers.get('set-cookie'))['XSRF-TOKEN'].value

        self.session.headers.update({'X-XSRF-TOKEN': token})

        res = self.session.get(self.host + '/api/devices', timeout=TIMEOUT, verify=False)
        if res.status_code == 200:
            return True
        return False

    def _log_out(self):
        self.session.get(self.host + '/api/logout', timeout=TIMEOUT, verify=False)
        self.session.close()
```

**Comment by cisasteelersfan** [comment]
Fixed by #8 

I just published version 0.0.4 to [Pypi](https://pypi.org/project/quantum-gateway/). Can you install that version and just test once more that it works with your router? I will then open a PR with HomeAssistant with the bumped version.

Thanks!

**Comment by PeterPlatt** [comment]
Close you'll need to change 
```
self.verify = use_https
```
to
```
self.verify = False
```
I was using that field var to disable the verify check. Fios is using a self-signed cert.

It's the current form it will not work. 


This is the error I got 
```
Traceback (most recent call last):
  File "/home/sly/.local/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/sly/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sly/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: /api/devices (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
```

**Comment by cisasteelersfan** [comment]
Ah yes, my bad. Fixed in https://github.com/cisasteelersfan/quantum_gateway/pull/11/files and just published v0.0.5 to Pypi. Thanks for troubleshooting!

**Comment by PeterPlatt** [comment]
That fixed it. For the Home assistant portion, I'd recommend an extra toggle like useHttps to toggle between to two. I have no idea about the adoption of the new firmware/ui. You can close out these defect.

**Comment by cisasteelersfan** [comment]
PR with Home Assistant: https://github.com/home-assistant/home-assistant/pull/21669

**Comment by Hackashaq666** [comment]
I have been using this ever since it was realeased and it works great.
However, I cannot get the new fixed version to work as a custom component as I wait for the PR to be incorporated in homeassistant.  Is there a reason why I shouldn't expect this to work as a custom component? I placed the quantum_tracker.py file in \config\custom_components\device_tracker folder.  Any advice appreciated!

**Comment by cisasteelersfan** [comment]
Hmm that is strange, I can't think of why it wouldn't work as a custom component. Can you share the error message / relevant logs?

I'm not sure if this is what you've already done, but in order to use as a custom component you need to use the file [here](https://github.com/home-assistant/home-assistant/blob/2d9c58378c70807be3d5272f5a99304275b787b6/homeassistant/components/device_tracker/quantum_gateway.py) in my Home Assistant PR, *not* the `quantum_gateway.py` file found in this repository. 

When you drop that file in the `config/custom_components/device_tracker/` folder and start hass, it should install the new Pypi version (`[homeassistant.util.package] Attempting install of quantum-gateway==0.0.5`). You may also see warnings like `[homeassistant.loader] Integrations need to be in their own folder. Change device_tracker/quantum_gateway.py to quantum_gateway/device_tracker.py. This will stop working soon.` depending on the version you are running.

Let me know if you aren't able to get it running!

**Comment by Hackashaq666** [comment]
Thanks for the reply, the problem may be related to changes in how custom components work tarting with 0.89 release.

> Custom Components file structure change: A significant change in how the “under the hood” of Home Assistant works has led to forcing platforms to be resolved based off the component path, if it exists. Today, if you want, you can override the Hue light platform, but not the other parts of the Hue integration. If a future update evolves the Hue component, removing or changing internal methods that the custom platform relied upon, the custom platform will start failing (like this report). To avoid this, we’re going to no longer allow custom components to be partial overlays (just a platform). Instead, if you want to override a built-in platform, you will need to override the whole component. This is enforced by first resolving the platform as a component, and if it exists, limiting the lookup path to the component path.

**Comment by Hackashaq666** [comment]
Here is the error I get when attempting to use this as custom component:

`Error setting up platform quantum_gateway
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/device_tracker/__init__.py", line 189, in async_setup_platform
    raise HomeAssistantError("Invalid device_tracker platform.")
homeassistant.exceptions.HomeAssistantError: Invalid device_tracker platform.`

**Comment by cisasteelersfan** [comment]
Interesting. It looks to me like you may have the wrong `quantum_gateway.py` file in your custom_components. It has to be this file: https://github.com/home-assistant/home-assistant/blob/2d9c58378c70807be3d5272f5a99304275b787b6/homeassistant/components/device_tracker/quantum_gateway.py, not the `quantum_gateway.py` found in the `src` folder of this quantum_gateway repository.

**Comment by Hackashaq666** [comment]
You were correct, I was using the quantum_gateway.py from the SRC folder, not the PR.
Sorry for wasting your time!  
I am rebooting with correct version now...

**Comment by cisasteelersfan** [comment]
Hey, no worries!! This is a good indication I should change the filename to avoid confusion. Let me know if you still encounter problems.

**Comment by PeterPlatt** [comment]
PR is merged can I close this issue?

**Comment by cisasteelersfan** [comment]
Closed by https://github.com/home-assistant/home-assistant/pull/21669
